package com.example.chuong.librarymanagementapi.entity.Enum;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    BOOK_NOT_FOUND(404,HttpStatus.NOT_FOUND,"BOOK NOT FOUND"),
    CATEGORY_NOT_FOUND(404,HttpStatus.NOT_FOUND,"CATEGORY NOT FOUND"),
    CATEGORY_EXISTED(400,HttpStatus.BAD_REQUEST,"CATEGORY EXISTED"),
    USER_FALSE(400,HttpStatus.BAD_REQUEST,"USER FALSE"),
    PASSWORD_FALSE(400,HttpStatus.BAD_REQUEST,"PASSWORD FALSE"),
    USERNAME_EXISTED(400,HttpStatus.BAD_REQUEST,"USERNAME EXISTED"),
    USER_NOT_FOUND(404, HttpStatus.NOT_FOUND,"USER NOT FOUND"),
    BORROW_NOT_FOUND(404, HttpStatus.NOT_FOUND,"BORROW RECORD NOT FOUND"),
    BOOK_OUT_OF_STOCK(400,HttpStatus.BAD_REQUEST, "BOOK OUT OF STOCK"),
    ALREADY_RETURNED(400,HttpStatus.BAD_REQUEST, "BOOK ALREADY RETURNED"),
    INVALID_RETURN_DATE(400,HttpStatus.BAD_REQUEST, "RETURN DATE MUST BE AFTER BORROW DATE"),
    BORROW_LIMIT_EXCEEDED(400,HttpStatus.BAD_REQUEST, "USER HAS EXCEEDED MAXIMUM BORROW LIMIT (5 BOOKS)"),
    ALREADY_BORROWED(400,HttpStatus.BAD_REQUEST, "YOU HAVE ALREADY BORROWED THIS BOOK AND NOT RETURNED IT YET"),
    INVALID_SORT_FIELD(400,HttpStatus.BAD_REQUEST,"INVALID SORT FIELDS"),
    INVALID_PRICE_RANGE(400,HttpStatus.BAD_REQUEST,"INVALID PRICE RANGE"),
    INVALID_PAGINATION_PARAMS(400,HttpStatus.BAD_REQUEST,"INVALID PAGINATION PARAMS"),
    INVALID_REFRESH_TOKEN(401,HttpStatus.UNAUTHORIZED,"INVALID REFRESH TOKEN"),
    REFRESH_TOKEN_EXPIRED(401, HttpStatus.UNAUTHORIZED,"REFRESH TOKEN EXPIRED OR REVOKED"),
    EMAIL_EXISTED(400,HttpStatus.BAD_REQUEST,"EMAIL EXISTED"),
    USER_DISABLED(403, HttpStatus.UNAUTHORIZED, "ACCOUNT HAS BEEN DISABLED"),
    INVALID_TOTAL_QUANTITY(400, HttpStatus.BAD_REQUEST,"Không thể giảm tổng số lượng xuống thấp hơn số sách đang được mượn");

    private final int code;
    private final HttpStatus httpStatus;
    private final String message;


}
